### ISSUE TITLE
Additional functionality: Generate a standalone mod - QUESTIONS

### ISSUE THREAD

**Issue by ilwsm** [LennardF1989/BG3-BagsOfSorting#7]
According the readme:

> If you do not want to use Pouch of Wonders, because you are already using something else, the GUI now has the possibility to generate a standalone mod to work with the game.
> 
> Simply changes the Folder-value in the Treasure Table-tab to something other than PouchOfWonders. Set the Name-value to your desired TreasureTable, for example T_TUT_Chest_Potions for the Tutorial Chest.
> 

1. Give the screen example. What settings must be:
![image](https://github.com/LennardF1989/BG3-BagsOfSorting/assets/2471892/0ea5155e-3189-4452-9a52-7895391ee8b1)

2. Where to get the custom bag in GAME ?

👎

**Comment by ilwsm** [comment]
It is absolutely unclear what to do. Wasted an entire hour. !!!!!

**Comment by LennardF1989** [comment]
I'm pretty sure you are misunderstanding what the Treasure Table does in-game.

On the bottom-right you see Folder and Name. Folder is the name of the mod the treasuretable will be generated for, the name is the name of the targeted treasuretable.

In this case, by default, it would generate a TreasureTable that overrides the one bundled with Pouch Of Wonders by setting the name to "POW_TT". Which is okay, since that one is empty anyway.

If you just want to add some items to the tutorial chest and have another mod to get access to that, you can set folder to "ilwsmMod" or whatever you desire, and name to "TUT_Chest_Potions".

Generate PAKs, drop the PAK in your Mods folder, make sure it's enabled using your mod manager, and it should do its work.

**Comment by ilwsm** [comment]
POST SCREEN PLEASSE!
POST LINK TO MOD TUT_Chest_Potions , PLEASE 

IS IT HARD TO YOU?

**Comment by LennardF1989** [comment]
You literally posted a screenshot yourself, to which I refered in my explanation, which on its own is a tutorial.

No need to SCREAM USING CAPS. The last sentence is uncalled for, passive aggresive and entitled. Please settle down.

**Comment by ilwsm** [comment]
Fuck you

**Comment by ilwsm** [comment]
2 hours - without success !!

**Comment by ilwsm** [comment]
The most stupid tutorial ever seen

**Comment by ilwsm** [comment]
What the ***** `TUT_Chest_Potions` ?

**Comment by ilwsm** [comment]
Where i can get bag ? Absolutely unclear

**Comment by ilwsm** [comment]
Is it possible to add bags to camp chest?

**Comment by LennardF1989** [comment]
Version 1.4.0 has been released.

This version allows you to bundle [Pouch of Wonders](https://www.nexusmods.com/baldursgate3/mods/1368) with a click of a button, meaning you can create bags, add items (by searching for them) and give them to yourself in-game by using the Pouch of Wonders spell on your hotbar.

Also see here for more direct instructions: https://www.nexusmods.com/baldursgate3/articles/204

No, it's not possible to add items to the camp chest.
